In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from scipy.special import expit as sigmoid
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import Ridge, LinearRegression

In [2]:
from utils import DataHandler
from ESN import EchoStateNetwork
from reservoirs import CPRC, GBPermanents, GBSampling
from properties import verify_ESP, memory_capacity, res_task

In [3]:
N = 500
train_size = 375
window_size = 20

In [4]:
X, Y = DataHandler().load_dataset('narma', n_samples = N, window_size=window_size, plot=False)
# X, Y, Y_ = DataHandler().load_dataset('mixed_waves',n=10, total_points = 2000, window_size=10, plot=True, seed = 58)

In [5]:
# Split into training and testing sets
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = Y[:train_size], Y[train_size:]

In [6]:
aaa = X_test[2]
aaa

array([0.4016628 , 0.42037819, 0.32498863, 0.46260502, 0.20502559,
       0.36399109, 0.48976827, 0.47232381, 0.43193401, 0.48641187,
       0.48746136, 0.40008747, 0.41724842, 0.15720343, 0.00317822,
       0.25644009, 0.1311196 , 0.48703941, 0.04225413, 0.27131497])

In [9]:
dim=len(X_train[0])
cprc = CPRC(dim=dim, execution_mode='simulation')
gbs = GBSampling()

In [10]:
from tqdm import tqdm
cprc_states = []
for sample in tqdm(X_train, desc="Processing Quantum Reservoir States"):
    state = cprc.qc_func(sample)
    print(state)
    cprc_states.append(state)

cprc_states = np.array(cprc_states)
print("Quantum Reservoir States Shape:", cprc_states.shape)

Processing Quantum Reservoir States:   1%|      | 3/375 [00:00<00:38,  9.63it/s]

[0.00181379 0.00067578 0.00044984 ... 0.00022674 0.00045108 0.00014003]
[0.00180251 0.00111471 0.00034191 ... 0.00014618 0.00032057 0.0002835 ]
[0.00154973 0.00062411 0.00048211 ... 0.00017161 0.0004491  0.00016141]


Processing Quantum Reservoir States:   1%|      | 5/375 [00:00<00:36, 10.15it/s]

[0.00206364 0.0007423  0.00028645 ... 0.00016533 0.00050375 0.00017279]
[0.00249608 0.00091382 0.00043766 ... 0.00021456 0.00040469 0.00025598]
[0.00160003 0.00067704 0.00060372 ... 0.00021671 0.00061895 0.00025364]


Processing Quantum Reservoir States:   2%|▏     | 9/375 [00:00<00:34, 10.50it/s]

[0.00202014 0.00090641 0.00029539 ... 0.00028968 0.00045046 0.00027338]
[0.00187277 0.00092953 0.00039244 ... 0.00024886 0.00036726 0.00027104]
[0.00136966 0.00069639 0.00038472 ... 0.00022562 0.00044269 0.00023584]


Processing Quantum Reservoir States:   3%|▏    | 11/375 [00:01<00:35, 10.37it/s]

[2.13543802e-03 6.74926194e-04 3.66013850e-04 ... 1.87370961e-04
 5.64161288e-04 3.13658969e-05]
[0.00203072 0.00096654 0.00028473 ... 0.00028471 0.0004794  0.00027034]
[0.00134447 0.00072324 0.00045841 ... 0.00026485 0.00044086 0.00038348]


Processing Quantum Reservoir States:   4%|▏    | 15/375 [00:01<00:34, 10.37it/s]

[1.89006130e-03 6.93795945e-04 4.11517375e-04 ... 2.03826132e-04
 4.10141852e-04 7.29747520e-05]
[1.93863573e-03 1.28126859e-03 3.13437779e-04 ... 1.60728836e-04
 3.54167472e-04 7.74214570e-05]
[2.32422085e-03 5.92157234e-04 6.34081987e-04 ... 1.89329236e-04
 5.70949251e-04 9.79358150e-05]
[0.00215623 0.00124791 0.00045553 ... 0.00017377 0.00033857 0.00026949]


Processing Quantum Reservoir States:   5%|▏    | 18/375 [00:02<00:47,  7.54it/s]

[0.00169893 0.00105309 0.00044312 ... 0.00017146 0.00020396 0.00034072]
[2.16872809e-03 7.74265984e-04 3.33599295e-04 ... 1.23751661e-04
 3.12630881e-04 1.65410473e-05]
[2.52171652e-03 1.36193539e-03 3.36345784e-04 ... 9.98247695e-05
 3.55358738e-04 3.08651270e-05]


Processing Quantum Reservoir States:   6%|▎    | 22/375 [00:02<00:39,  9.01it/s]

[1.60456567e-03 7.69274894e-04 7.54791654e-04 ... 8.37871014e-05
 4.34824390e-04 3.40547256e-04]
[0.00189523 0.0008712  0.00047968 ... 0.00011446 0.00036754 0.000356  ]
[0.00281351 0.00096027 0.00038086 ... 0.00018632 0.00040966 0.00012794]


Processing Quantum Reservoir States:   6%|▎    | 24/375 [00:02<00:37,  9.44it/s]

[0.00180779 0.0009598  0.00047924 ... 0.00018196 0.00039412 0.00025631]
[0.00203737 0.00085542 0.0004958  ... 0.00016353 0.00042769 0.00026081]
[0.00153214 0.00096973 0.00043517 ... 0.00015592 0.00035517 0.00046647]


Processing Quantum Reservoir States:   7%|▎    | 28/375 [00:02<00:34, 10.12it/s]

[1.50858776e-03 4.60249590e-04 3.30238790e-04 ... 3.18995878e-04
 8.17764516e-04 9.60225469e-05]
[0.00204647 0.00112436 0.0002247  ... 0.00031767 0.00029766 0.00035995]
[0.00131063 0.00057868 0.00057564 ... 0.00026957 0.0004612  0.00023898]


Processing Quantum Reservoir States:   8%|▍    | 30/375 [00:03<00:33, 10.23it/s]

[0.00132839 0.00062241 0.00032725 ... 0.00018349 0.00047409 0.00018445]
[2.10467581e-03 9.44363480e-04 2.28421442e-04 ... 1.76830466e-04
 2.79674575e-04 4.62524478e-05]
[0.00227816 0.00064129 0.00046399 ... 0.00018789 0.00052248 0.00022541]


Processing Quantum Reservoir States:   9%|▍    | 34/375 [00:03<00:32, 10.39it/s]

[0.00154575 0.00093785 0.00047117 ... 0.00019563 0.00044333 0.00024976]
[0.00219699 0.00079362 0.00053602 ... 0.00016743 0.00043941 0.0002078 ]
[0.00188067 0.00114209 0.0002197  ... 0.00022298 0.00026591 0.00023246]


Processing Quantum Reservoir States:  10%|▍    | 36/375 [00:03<00:32, 10.44it/s]

[2.10640733e-03 6.75719451e-04 5.52661168e-04 ... 1.25179296e-04
 4.75172677e-04 4.92932196e-05]
[0.00228851 0.00097078 0.00034004 ... 0.00016364 0.00037751 0.00012165]
[0.00176166 0.0010291  0.00040384 ... 0.0001477  0.00038622 0.00035575]


Processing Quantum Reservoir States:  11%|▌    | 40/375 [00:04<00:31, 10.54it/s]

[0.0019073  0.00048088 0.00045409 ... 0.00031134 0.00061066 0.00021038]
[0.0016753  0.00141417 0.00031408 ... 0.00018395 0.00027146 0.00022681]
[2.34053163e-03 4.48045124e-04 5.75408358e-04 ... 2.18837902e-04
 5.51458258e-04 9.39948080e-05]


Processing Quantum Reservoir States:  11%|▌    | 42/375 [00:04<00:31, 10.57it/s]

[0.00177413 0.00096855 0.00042936 ... 0.00020135 0.00052116 0.00024466]
[0.00182399 0.00095861 0.00042667 ... 0.00025391 0.00035395 0.00051365]
[0.00184351 0.00064199 0.00040413 ... 0.00024146 0.00037248 0.00016946]


Processing Quantum Reservoir States:  12%|▌    | 46/375 [00:04<00:31, 10.60it/s]

[1.99389971e-03 1.01792328e-03 1.82393418e-04 ... 1.87721875e-04
 3.34713127e-04 6.24742849e-05]
[0.00160315 0.00066207 0.000493   ... 0.00017397 0.00043165 0.00016456]
[0.0017229  0.00087218 0.00034149 ... 0.00012616 0.00039069 0.00029005]


Processing Quantum Reservoir States:  13%|▋    | 48/375 [00:04<00:30, 10.63it/s]

[0.00202826 0.00075571 0.00037985 ... 0.00015189 0.00039322 0.00021292]
[2.20846285e-03 6.49003230e-04 4.53162585e-04 ... 2.60076417e-04
 6.17285751e-04 2.40098051e-05]
[0.00260098 0.00141273 0.00030539 ... 0.00019537 0.00029179 0.00031732]


Processing Quantum Reservoir States:  14%|▋    | 52/375 [00:05<00:35,  9.05it/s]

[0.00162163 0.00068401 0.00080961 ... 0.0001769  0.00038783 0.00032316]
[0.0016434  0.00075315 0.00035384 ... 0.00015475 0.00043284 0.000222  ]
[2.71922736e-03 9.94351379e-04 2.46617481e-04 ... 1.76269976e-04
 3.38321009e-04 9.91079549e-05]


Processing Quantum Reservoir States:  14%|▋    | 54/375 [00:05<00:33,  9.50it/s]

[0.00185347 0.00069511 0.00050066 ... 0.0002163  0.0005373  0.00031997]
[0.00136953 0.00078579 0.0004167  ... 0.00022218 0.00049888 0.00036439]
[0.0017362  0.00083391 0.00031527 ... 0.00020959 0.00031298 0.00029606]


Processing Quantum Reservoir States:  15%|▊    | 58/375 [00:05<00:31, 10.12it/s]

[2.11829188e-03 6.81105110e-04 3.08333962e-04 ... 2.29452540e-04
 4.80620820e-04 7.21236561e-05]
[0.00198428 0.00084481 0.00053094 ... 0.00021437 0.00056018 0.00010719]
[0.00161543 0.00090773 0.00054119 ... 0.0002306  0.000437   0.00033581]


Processing Quantum Reservoir States:  16%|▊    | 60/375 [00:06<00:30, 10.27it/s]

[0.00177504 0.00091633 0.00028233 ... 0.00021339 0.00027228 0.00046565]
[2.07984228e-03 7.25028794e-04 3.41522436e-04 ... 2.03549720e-04
 3.48061159e-04 4.46656284e-06]
[2.25319312e-03 1.12235560e-03 3.76887885e-04 ... 1.03530975e-04
 4.14862031e-04 8.75426117e-05]


Processing Quantum Reservoir States:  17%|▊    | 64/375 [00:06<00:29, 10.41it/s]

[0.00200148 0.00077367 0.00060304 ... 0.00013595 0.00043253 0.00022048]
[0.00163073 0.00086533 0.00059332 ... 0.00011484 0.00043128 0.00049557]
[2.46804005e-03 7.83104334e-04 4.01565375e-04 ... 2.69332418e-04
 4.99975636e-04 5.63201229e-05]


Processing Quantum Reservoir States:  18%|▉    | 66/375 [00:06<00:29, 10.41it/s]

[0.0022717  0.00145995 0.00035993 ... 0.00017836 0.00030059 0.00024557]
[0.00153797 0.00076617 0.00068566 ... 0.00016218 0.00036458 0.0001869 ]
[1.98922468e-03 7.77947286e-04 4.32060937e-04 ... 9.89539349e-05
 4.44762373e-04 1.98911903e-04]


Processing Quantum Reservoir States:  19%|▉    | 70/375 [00:07<00:28, 10.59it/s]

[0.00230913 0.00101463 0.00016813 ... 0.00019919 0.0003534  0.00013055]
[0.002048   0.00064318 0.0004902  ... 0.00018739 0.00054945 0.0002562 ]
[0.00152534 0.00088097 0.00043546 ... 0.00022071 0.00039808 0.00028407]


Processing Quantum Reservoir States:  19%|▉    | 72/375 [00:07<00:28, 10.63it/s]

[0.0019374  0.0006855  0.00052008 ... 0.00017117 0.00056757 0.00018705]
[0.00219956 0.00079859 0.00033102 ... 0.00031318 0.00051267 0.0002748 ]
[0.00180106 0.00094785 0.0004863  ... 0.00021981 0.00038706 0.00031188]


Processing Quantum Reservoir States:  20%|█    | 76/375 [00:07<00:28, 10.54it/s]

[0.00191095 0.00059872 0.00042841 ... 0.00029182 0.00048642 0.00015958]
[0.00184902 0.0010605  0.00019645 ... 0.00020556 0.00041048 0.00015567]
[0.00166434 0.0006052  0.00033945 ... 0.00025851 0.00042985 0.00019504]


Processing Quantum Reservoir States:  21%|█    | 78/375 [00:07<00:28, 10.53it/s]

[0.00173864 0.00073735 0.00042631 ... 0.00018848 0.00054522 0.000134  ]
[0.00205106 0.00077962 0.0003851  ... 0.00019776 0.00051307 0.00020929]
[0.00207464 0.00073576 0.00049985 ... 0.00027934 0.0005977  0.00017286]


Processing Quantum Reservoir States:  22%|█    | 82/375 [00:08<00:27, 10.64it/s]

[0.00215814 0.00121942 0.00030087 ... 0.00024627 0.00023677 0.00043589]
[1.97106378e-03 6.73439626e-04 5.23658934e-04 ... 1.80897168e-04
 3.63457381e-04 5.90386299e-05]
[2.23571558e-03 9.05450471e-04 2.98815714e-04 ... 1.49192855e-04
 5.13516297e-04 5.62462343e-05]


Processing Quantum Reservoir States:  22%|█    | 84/375 [00:08<00:27, 10.57it/s]

[0.00198568 0.00095343 0.00039041 ... 0.00019705 0.00040858 0.00021479]
[0.00161582 0.00067418 0.00059233 ... 0.00017554 0.00049524 0.00046464]
[0.00195695 0.00085755 0.00034436 ... 0.00022502 0.00041834 0.00012371]


Processing Quantum Reservoir States:  23%|█▏   | 88/375 [00:08<00:26, 10.65it/s]

[0.00242939 0.00102867 0.00038737 ... 0.00016911 0.00041643 0.00010682]
[0.0021047  0.0008475  0.00052312 ... 0.00020505 0.00043989 0.00019986]
[0.00171489 0.00096491 0.00054359 ... 0.00015916 0.00042064 0.00030065]


Processing Quantum Reservoir States:  24%|█▏   | 90/375 [00:08<00:26, 10.68it/s]

[0.00181813 0.00081543 0.00036882 ... 0.00024485 0.00043463 0.00015077]
[0.00210755 0.00104752 0.00028054 ... 0.00018364 0.00036287 0.00014956]
[0.0016377  0.00094258 0.00047444 ... 0.00016786 0.00029703 0.00014322]


Processing Quantum Reservoir States:  25%|█▎   | 94/375 [00:09<00:26, 10.72it/s]

[1.99605421e-03 7.57260429e-04 5.51639024e-04 ... 1.05920809e-04
 5.02381275e-04 5.61323695e-05]
[0.00277722 0.00110863 0.00029407 ... 0.00018037 0.00039813 0.0001314 ]
[0.00190882 0.00093604 0.00059635 ... 0.00018754 0.00044402 0.00024548]


Processing Quantum Reservoir States:  26%|█▎   | 96/375 [00:09<00:25, 10.73it/s]

[0.00192428 0.00081663 0.00055042 ... 0.00020143 0.00042226 0.00024003]
[0.00187927 0.00129957 0.00047419 ... 0.00017569 0.00029337 0.00020193]
[0.00204541 0.0007091  0.00049627 ... 0.00018915 0.00048147 0.00014178]


Processing Quantum Reservoir States:  26%|█▎   | 98/375 [00:09<00:26, 10.63it/s]

[0.00207991 0.00101967 0.00038898 ... 0.00018298 0.00039378 0.00019046]


Processing Quantum Reservoir States:  27%|█   | 100/375 [00:10<00:32,  8.37it/s]

[0.00158083 0.00097639 0.00042419 ... 0.00019015 0.00029835 0.00036013]
[1.69416447e-03 6.60378939e-04 3.30228743e-04 ... 2.02809119e-04
 4.56576004e-04 7.56124258e-05]
[2.05092128e-03 1.05967018e-03 2.74348952e-04 ... 1.82086260e-04
 3.87079185e-04 7.25837347e-05]


Processing Quantum Reservoir States:  28%|█   | 104/375 [00:10<00:28,  9.43it/s]

[0.00151952 0.00074948 0.00064678 ... 0.00020435 0.00050223 0.00012644]
[0.00191269 0.00077444 0.00052745 ... 0.00017757 0.00050044 0.00028551]
[0.00195723 0.00126132 0.00036444 ... 0.00020243 0.00022755 0.00030722]


Processing Quantum Reservoir States:  28%|█▏  | 106/375 [00:10<00:27,  9.85it/s]

[2.08133723e-03 7.06957010e-04 5.07569465e-04 ... 1.89626558e-04
 4.00710714e-04 7.18308901e-05]
[2.31390527e-03 1.26502452e-03 2.57650951e-04 ... 1.37457061e-04
 2.59881022e-04 9.60145060e-05]
[0.00175711 0.00082783 0.00065991 ... 0.00016607 0.00046344 0.00010389]


Processing Quantum Reservoir States:  29%|█▏  | 110/375 [00:10<00:25, 10.29it/s]

[0.00146107 0.00080463 0.00040217 ... 0.0001491  0.00042356 0.00039621]
[0.00200719 0.00092894 0.00037174 ... 0.00018498 0.0003434  0.00015521]
[2.19177899e-03 6.63371644e-04 5.65111933e-04 ... 2.17868573e-04
 5.59001256e-04 9.11696228e-05]


Processing Quantum Reservoir States:  30%|█▏  | 112/375 [00:11<00:25, 10.38it/s]

[0.00195044 0.00109956 0.00043267 ... 0.00023191 0.00051939 0.00022499]
[0.0018818  0.00083097 0.00059759 ... 0.00026877 0.00043023 0.00045098]
[0.00117542 0.00093375 0.00029126 ... 0.00026152 0.00020948 0.00045249]


Processing Quantum Reservoir States:  31%|█▏  | 116/375 [00:11<00:24, 10.57it/s]

[1.84589979e-03 6.17188622e-04 2.89174403e-04 ... 1.39099808e-04
 3.66725806e-04 4.63311733e-05]
[2.23152684e-03 8.18781417e-04 3.29740168e-04 ... 1.61256202e-04
 4.64449911e-04 7.57579811e-06]
[0.00137388 0.00094064 0.00050602 ... 0.00013351 0.0004924  0.00044669]


Processing Quantum Reservoir States:  31%|█▎  | 118/375 [00:11<00:24, 10.63it/s]

[0.00168923 0.0004836  0.00054135 ... 0.00025546 0.00057294 0.00026544]
[0.00201845 0.00128559 0.00019274 ... 0.00018945 0.00025274 0.0001361 ]
[2.66449914e-03 5.22695737e-04 6.36506274e-04 ... 2.26893757e-04
 5.05293854e-04 5.87386164e-06]


Processing Quantum Reservoir States:  33%|█▎  | 122/375 [00:12<00:23, 10.68it/s]

[0.0018765  0.00118601 0.00053391 ... 0.00015788 0.00044009 0.00028997]
[0.00187252 0.00072087 0.00062955 ... 0.000225   0.00046778 0.00048536]
[0.00157653 0.00083841 0.00028953 ... 0.00025553 0.00033345 0.0004414 ]


Processing Quantum Reservoir States:  33%|█▎  | 124/375 [00:12<00:23, 10.65it/s]

[2.07630283e-03 8.51065489e-04 2.61056382e-04 ... 2.00973094e-04
 2.89081260e-04 1.04919936e-05]
[1.93773849e-03 8.39473701e-04 4.76153886e-04 ... 1.47019055e-04
 4.55645639e-04 5.91011678e-05]
[0.00128605 0.0007853  0.00046033 ... 0.000157   0.00056219 0.00020304]


Processing Quantum Reservoir States:  34%|█▎  | 128/375 [00:12<00:23, 10.59it/s]

[0.00208231 0.00069577 0.0003843  ... 0.00019087 0.00051802 0.00032564]
[0.00205019 0.00100468 0.00027947 ... 0.00026535 0.00032554 0.00014527]
[2.17317442e-03 8.56257715e-04 4.89506419e-04 ... 1.41524970e-04
 3.88327707e-04 8.10743236e-05]


Processing Quantum Reservoir States:  35%|█▍  | 130/375 [00:12<00:23, 10.63it/s]

[2.27727199e-03 8.22407183e-04 5.58313073e-04 ... 1.85887561e-04
 4.68400559e-04 3.86373155e-05]
[0.00176231 0.00122943 0.00051259 ... 0.00012299 0.00044497 0.00051999]
[0.0019832  0.0005705  0.00054844 ... 0.00033665 0.0005958  0.00031029]


Processing Quantum Reservoir States:  36%|█▍  | 134/375 [00:13<00:22, 10.73it/s]

[0.00194929 0.00119853 0.0002933  ... 0.00018896 0.00032267 0.00022406]
[0.0017271  0.00080956 0.00039824 ... 0.00023114 0.00031555 0.00013205]
[1.88670044e-03 7.23566597e-04 4.30414063e-04 ... 1.28390733e-04
 5.32858245e-04 9.26468869e-05]


Processing Quantum Reservoir States:  36%|█▍  | 136/375 [00:13<00:22, 10.64it/s]

[0.00207618 0.00096064 0.00026575 ... 0.00020707 0.00039486 0.00022939]
[0.00163266 0.00072556 0.0004723  ... 0.00018206 0.00045553 0.00024486]
[0.00234693 0.00079459 0.0003487  ... 0.00021532 0.00042836 0.00010375]


Processing Quantum Reservoir States:  37%|█▍  | 140/375 [00:13<00:21, 10.73it/s]

[0.00205633 0.00117465 0.00050938 ... 0.00015945 0.0004059  0.00011986]
[0.00188897 0.00060369 0.00065377 ... 0.00025746 0.00068408 0.00018807]
[0.00178811 0.00138921 0.00032286 ... 0.00020794 0.00022885 0.00052563]


Processing Quantum Reservoir States:  38%|█▌  | 142/375 [00:13<00:21, 10.68it/s]

[0.00199746 0.00062679 0.00052086 ... 0.00022617 0.00039574 0.00011095]
[1.94493483e-03 9.82720491e-04 2.46811142e-04 ... 1.58838710e-04
 3.69903855e-04 8.75562450e-05]
[2.04663567e-03 9.27387147e-04 3.82922562e-04 ... 1.74938039e-04
 3.14727598e-04 9.93281902e-05]


Processing Quantum Reservoir States:  39%|█▌  | 146/375 [00:14<00:21, 10.64it/s]

[0.0014917  0.00079086 0.00051979 ... 0.00011273 0.00038843 0.00035468]
[1.84273620e-03 7.65168609e-04 3.11087839e-04 ... 1.81729968e-04
 4.52874294e-04 3.90192224e-05]
[2.70307498e-03 8.26379497e-04 4.92328433e-04 ... 1.78586186e-04
 5.48342363e-04 6.18807150e-05]


Processing Quantum Reservoir States:  39%|█▌  | 148/375 [00:14<00:21, 10.64it/s]

[0.00173531 0.0011382  0.0005102  ... 0.0001863  0.00042792 0.00050354]
[0.00191034 0.00066261 0.00071204 ... 0.0001705  0.00040018 0.00039914]
[0.00201168 0.00102835 0.00022783 ... 0.00021105 0.00027475 0.00015833]


Processing Quantum Reservoir States:  40%|█▌  | 150/375 [00:14<00:21, 10.59it/s]

[0.00227634 0.00078172 0.0002945  ... 0.0001358  0.00043698 0.00011142]


Processing Quantum Reservoir States:  41%|█▌  | 152/375 [00:15<00:27,  8.14it/s]

[0.00180257 0.0007249  0.00040008 ... 0.00020667 0.00044857 0.00023394]
[0.00138216 0.00080771 0.00047923 ... 0.00016374 0.00048044 0.00040908]
[0.00190454 0.00050911 0.00028388 ... 0.000281   0.00060479 0.00017626]


Processing Quantum Reservoir States:  42%|█▋  | 156/375 [00:15<00:23,  9.29it/s]

[0.00233982 0.00087798 0.00031877 ... 0.00024611 0.00052543 0.00012946]
[0.00202434 0.00061422 0.00065154 ... 0.00030827 0.00063857 0.00034483]
[0.00139719 0.00092529 0.00044469 ... 0.00022212 0.00041621 0.00053028]


Processing Quantum Reservoir States:  42%|█▋  | 158/375 [00:15<00:22,  9.64it/s]

[0.00215489 0.00072862 0.00029139 ... 0.00031526 0.00037104 0.00026376]
[1.74641704e-03 8.66477378e-04 2.28198942e-04 ... 2.31854059e-04
 3.50746219e-04 7.36963118e-05]
[1.79903141e-03 6.67354148e-04 3.38739609e-04 ... 1.67574993e-04
 4.96399117e-04 3.86678277e-05]


Processing Quantum Reservoir States:  43%|█▋  | 162/375 [00:16<00:21, 10.08it/s]

[0.0019512  0.00071151 0.00036862 ... 0.00020097 0.00052532 0.00015083]
[0.00157437 0.00085464 0.00032867 ... 0.00018895 0.00043994 0.00041268]
[2.34227193e-03 5.75311244e-04 4.54427626e-04 ... 2.41392212e-04
 5.08116919e-04 8.57803405e-05]


Processing Quantum Reservoir States:  44%|█▋  | 164/375 [00:16<00:20, 10.20it/s]

[0.00248369 0.00136566 0.00036311 ... 0.00016119 0.00032697 0.00011289]
[0.00237025 0.00071932 0.00071629 ... 0.00017369 0.00050192 0.00015233]
[0.00198053 0.0011627  0.00038576 ... 0.0001597  0.00030507 0.00043281]


Processing Quantum Reservoir States:  45%|█▊  | 168/375 [00:16<00:19, 10.53it/s]

[0.00218949 0.0008569  0.00030894 ... 0.00018877 0.00031002 0.00014475]
[2.12965867e-03 7.86681988e-04 3.35856154e-04 ... 1.65222524e-04
 4.55279895e-04 8.09141751e-05]
[1.99331797e-03 8.79231524e-04 4.24661243e-04 ... 1.94725549e-04
 5.65307859e-04 8.01489122e-05]


Processing Quantum Reservoir States:  45%|█▊  | 170/375 [00:16<00:19, 10.61it/s]

[0.00177769 0.00081106 0.00056244 ... 0.00019916 0.00053765 0.00049399]
[0.00159341 0.00076001 0.00046595 ... 0.00026623 0.0004955  0.00036313]
[0.00205924 0.00103495 0.00035559 ... 0.0002226  0.00034326 0.00017153]


Processing Quantum Reservoir States:  46%|█▊  | 174/375 [00:17<00:18, 10.65it/s]

[2.10018172e-03 8.69460026e-04 4.84026325e-04 ... 2.00859982e-04
 3.75879083e-04 2.51659184e-05]
[0.00180783 0.00106821 0.00040262 ... 0.00015    0.00042412 0.00021291]
[0.0015245  0.00074039 0.00041671 ... 0.00021675 0.00040721 0.00014325]


Processing Quantum Reservoir States:  47%|█▉  | 176/375 [00:17<00:18, 10.69it/s]

[0.00167878 0.00104846 0.00027471 ... 0.00012605 0.00030093 0.00021539]
[2.08506344e-03 8.46046172e-04 3.48710579e-04 ... 1.37165613e-04
 2.76580794e-04 5.16025926e-06]
[2.38205679e-03 9.43354779e-04 6.66137710e-04 ... 7.43758419e-05
 4.71026881e-04 5.13458095e-05]


Processing Quantum Reservoir States:  48%|█▉  | 180/375 [00:17<00:18, 10.64it/s]

[0.00270439 0.00094194 0.0006145  ... 0.00015897 0.00052422 0.00020501]
[0.00186681 0.00121962 0.00064703 ... 0.00010572 0.00025457 0.00069545]
[0.00209799 0.00071754 0.00048756 ... 0.00024756 0.0004121  0.00011572]


Processing Quantum Reservoir States:  49%|█▉  | 182/375 [00:17<00:18, 10.62it/s]

[0.00214009 0.00133441 0.00038078 ... 0.00010602 0.00032858 0.00018825]
[0.00163031 0.00068489 0.00045467 ... 0.00015823 0.00045209 0.00018185]
[0.00171482 0.00065857 0.00038998 ... 0.00017779 0.00059354 0.00037698]


Processing Quantum Reservoir States:  50%|█▉  | 186/375 [00:18<00:17, 10.71it/s]

[0.00162721 0.00080436 0.00023397 ... 0.00033904 0.00043795 0.00044402]
[0.00166395 0.00057956 0.0004319  ... 0.00028288 0.00056211 0.00019882]
[0.0018153  0.00080459 0.00039644 ... 0.00031017 0.00043524 0.00021344]


Processing Quantum Reservoir States:  50%|██  | 188/375 [00:18<00:17, 10.70it/s]

[0.00125856 0.00086861 0.0005314  ... 0.00016323 0.00047744 0.00022255]
[0.0020425  0.00060509 0.00042882 ... 0.00031163 0.00053212 0.00012712]
[0.00202329 0.00129081 0.0001903  ... 0.00021256 0.00024421 0.00016955]


Processing Quantum Reservoir States:  51%|██  | 192/375 [00:18<00:17, 10.75it/s]

[1.63393670e-03 5.30960334e-04 4.43922841e-04 ... 2.28387543e-04
 3.95138645e-04 4.59724012e-05]
[2.04800591e-03 1.12141217e-03 2.85092130e-04 ... 1.00054305e-04
 3.46253104e-04 4.86801588e-05]
[0.00204158 0.00083916 0.00043185 ... 0.00011565 0.00031657 0.00012074]


Processing Quantum Reservoir States:  52%|██  | 194/375 [00:19<00:16, 10.75it/s]

[0.00199758 0.00061017 0.00067424 ... 0.00013085 0.00059512 0.00015122]
[0.00302106 0.00114475 0.00045151 ... 0.00018194 0.00039211 0.00028234]
[0.00224339 0.00101972 0.00063752 ... 0.00017916 0.00037117 0.00033021]


Processing Quantum Reservoir States:  53%|██  | 198/375 [00:19<00:16, 10.69it/s]

[0.00191571 0.00079987 0.00037625 ... 0.00023932 0.00045452 0.00024039]
[0.00181552 0.00119563 0.00034311 ... 0.00020481 0.00030674 0.00027519]
[0.00133553 0.00062815 0.00038995 ... 0.00020428 0.00047914 0.00022273]


Processing Quantum Reservoir States:  53%|██▏ | 200/375 [00:19<00:16, 10.70it/s]

[0.00170247 0.00072271 0.00024308 ... 0.00020332 0.00048847 0.00018387]
[0.00180268 0.00075484 0.00034216 ... 0.00026868 0.00046643 0.00011023]
[0.00170304 0.00075817 0.000396   ... 0.0002524  0.00051726 0.00021307]


Processing Quantum Reservoir States:  54%|██▏ | 202/375 [00:19<00:16, 10.71it/s]

[0.00177173 0.00096791 0.0003521  ... 0.0002082  0.00028981 0.0001811 ]
[2.17302856e-03 7.63979425e-04 5.16053036e-04 ... 1.47118192e-04
 4.40597367e-04 3.79674528e-05]


Processing Quantum Reservoir States:  55%|██▏ | 206/375 [00:20<00:18,  8.91it/s]

[0.00256257 0.00096335 0.00041212 ... 0.00017788 0.00046562 0.00010937]
[0.0020772  0.00109751 0.0005635  ... 0.00015328 0.0003498  0.00036217]
[0.00213857 0.00073487 0.00051368 ... 0.00019264 0.0004386  0.00025459]


Processing Quantum Reservoir States:  55%|██▏ | 208/375 [00:20<00:17,  9.36it/s]

[0.00225316 0.00107694 0.00031177 ... 0.00019918 0.00042375 0.00011916]
[0.00182743 0.00089475 0.00046271 ... 0.00018727 0.0004248  0.00026138]
[0.00184132 0.00073509 0.00047414 ... 0.00018177 0.00049108 0.00028699]


Processing Quantum Reservoir States:  57%|██▎ | 212/375 [00:20<00:16, 10.00it/s]

[0.00178488 0.00088187 0.00039358 ... 0.0002126  0.00046998 0.00028343]
[0.00167001 0.0007742  0.00034848 ... 0.0002683  0.00047538 0.00020375]
[0.00233    0.00086344 0.00038778 ... 0.00021758 0.00035344 0.00018023]


Processing Quantum Reservoir States:  57%|██▎ | 214/375 [00:21<00:15, 10.13it/s]

[0.00145621 0.0009747  0.00045773 ... 0.00018697 0.00038127 0.00015718]
[1.69466852e-03 5.97547322e-04 4.77632258e-04 ... 2.03839269e-04
 6.64406923e-04 5.06874945e-05]
[0.00206126 0.00138827 0.00018058 ... 0.00019303 0.00023657 0.00030308]


Processing Quantum Reservoir States:  58%|██▎ | 218/375 [00:21<00:15, 10.44it/s]

[1.83245710e-03 6.64395001e-04 5.52677101e-04 ... 1.50933352e-04
 3.76865032e-04 7.83627552e-05]
[2.28419993e-03 8.10320018e-04 3.99556331e-04 ... 1.50576802e-04
 4.41075912e-04 2.66860942e-05]
[0.00255932 0.00131518 0.0004156  ... 0.00016164 0.00034016 0.00013496]


Processing Quantum Reservoir States:  59%|██▎ | 220/375 [00:21<00:14, 10.52it/s]

[0.00168741 0.00073714 0.00069796 ... 0.0001618  0.00047249 0.00047976]
[0.00165342 0.00092286 0.00044174 ... 0.00018558 0.00038    0.00020421]
[0.0023404  0.00105149 0.00042752 ... 0.00016508 0.00039145 0.00014772]


Processing Quantum Reservoir States:  60%|██▍ | 224/375 [00:22<00:14, 10.70it/s]

[0.00176425 0.00090852 0.00038567 ... 0.00019936 0.00039332 0.00020757]
[0.00172283 0.00079848 0.00047237 ... 0.00017097 0.00041241 0.00023514]
[0.00160942 0.00082235 0.00030708 ... 0.0002409  0.00041333 0.00014214]


Processing Quantum Reservoir States:  60%|██▍ | 226/375 [00:22<00:13, 10.75it/s]

[0.00180484 0.0008748  0.0002872  ... 0.0002031  0.00044345 0.0001329 ]
[0.00165085 0.00079588 0.00050886 ... 0.00023152 0.00041335 0.00011226]
[0.00164722 0.00092512 0.00058947 ... 0.00014466 0.00045177 0.00013054]


Processing Quantum Reservoir States:  61%|██▍ | 230/375 [00:22<00:13, 10.64it/s]

[0.00242584 0.00091229 0.00045944 ... 0.00020755 0.00041126 0.00013332]
[0.0020944  0.00122199 0.00042783 ... 0.00017319 0.00030103 0.00017604]
[0.00199316 0.0009287  0.0004648  ... 0.00015618 0.00026941 0.00014869]


Processing Quantum Reservoir States:  62%|██▍ | 232/375 [00:22<00:13, 10.63it/s]

[0.00188696 0.00110175 0.0004549  ... 0.00010372 0.00025036 0.00013284]
[1.98847288e-03 8.62651264e-04 4.23807820e-04 ... 9.73303095e-05
 3.83077176e-04 9.49642895e-05]
[0.0022463  0.00076022 0.0005704  ... 0.00016026 0.00062894 0.00012063]


Processing Quantum Reservoir States:  63%|██▌ | 236/375 [00:23<00:13, 10.69it/s]

[0.00176963 0.00109966 0.00052897 ... 0.00013356 0.00037874 0.00067999]
[0.00196159 0.00065314 0.00059068 ... 0.00023892 0.00046819 0.00032376]
[0.0021433  0.00102776 0.00027574 ... 0.00021145 0.00031298 0.0001838 ]


Processing Quantum Reservoir States:  63%|██▌ | 238/375 [00:23<00:12, 10.68it/s]

[0.00193844 0.00071837 0.00042741 ... 0.00021061 0.00049763 0.00012378]
[0.00160384 0.00067946 0.00035834 ... 0.00022358 0.00053991 0.00039646]
[0.00139116 0.00068913 0.00028281 ... 0.00029156 0.00050193 0.00047353]


Processing Quantum Reservoir States:  65%|██▌ | 242/375 [00:23<00:12, 10.60it/s]

[0.00155508 0.00049304 0.00030239 ... 0.00033321 0.00063158 0.00017571]
[0.00194327 0.00079809 0.00030066 ... 0.00033307 0.00049759 0.00012684]
[0.00156228 0.00072336 0.00047888 ... 0.00025227 0.00052065 0.00025561]


Processing Quantum Reservoir States:  65%|██▌ | 244/375 [00:23<00:12, 10.51it/s]

[0.00170733 0.00059489 0.00044904 ... 0.00030211 0.00060686 0.00019682]
[0.00216716 0.00106595 0.00022223 ... 0.00025281 0.00033526 0.0002207 ]
[1.93523454e-03 6.58432541e-04 3.82003188e-04 ... 2.72286138e-04
 3.81706377e-04 8.82938597e-05]


Processing Quantum Reservoir States:  66%|██▋ | 248/375 [00:24<00:11, 10.62it/s]

[0.00184207 0.0009758  0.00034139 ... 0.00013925 0.00038003 0.00012745]
[2.13684713e-03 7.03785648e-04 3.99338029e-04 ... 1.49424937e-04
 3.95059716e-04 7.10224891e-05]
[0.00219581 0.00085802 0.00041974 ... 0.00013593 0.00052402 0.00022441]


Processing Quantum Reservoir States:  67%|██▋ | 250/375 [00:24<00:11, 10.68it/s]

[0.00246239 0.00085803 0.00043128 ... 0.00020259 0.00042187 0.0002791 ]
[0.00233102 0.00088815 0.00057376 ... 0.000161   0.00041677 0.00020302]
[0.00245299 0.00089787 0.00038595 ... 0.00022981 0.00048878 0.00013727]


Processing Quantum Reservoir States:  68%|██▋ | 254/375 [00:24<00:11, 10.81it/s]

[0.00195911 0.00110967 0.00046308 ... 0.00018119 0.00042921 0.00034482]
[0.00151273 0.00076966 0.00040404 ... 0.00021347 0.00036041 0.000364  ]
[0.00209149 0.00073846 0.00030446 ... 0.00016976 0.00049971 0.00010345]


Processing Quantum Reservoir States:  68%|██▋ | 256/375 [00:25<00:10, 10.86it/s]

[2.14382096e-03 8.25353428e-04 3.14957859e-04 ... 2.66013671e-04
 5.29688797e-04 8.36234931e-05]
[0.00153848 0.00095443 0.00042712 ... 0.00022066 0.00041497 0.00040911]
[0.00166841 0.00067457 0.00040534 ... 0.00019571 0.00034352 0.00024982]


Processing Quantum Reservoir States:  69%|██▊ | 260/375 [00:25<00:10, 10.87it/s]

[2.09051827e-03 8.74753589e-04 3.39053045e-04 ... 1.32216246e-04
 4.38485075e-04 2.64727833e-05]
[2.77937610e-03 8.29095198e-04 3.65386283e-04 ... 1.63461961e-04
 4.67083459e-04 7.91292418e-05]
[0.00228247 0.00090303 0.00065962 ... 0.0001549  0.00045452 0.00038567]


Processing Quantum Reservoir States:  70%|██▊ | 262/375 [00:25<00:10, 10.86it/s]

[0.00164165 0.00089358 0.00053139 ... 0.00014397 0.00029813 0.00063867]
[2.38650337e-03 6.64011849e-04 3.73378813e-04 ... 2.08634606e-04
 5.23255676e-04 2.86098845e-05]
[0.00271357 0.00113663 0.00028946 ... 0.00021667 0.00041347 0.00017695]


Processing Quantum Reservoir States:  71%|██▊ | 266/375 [00:25<00:10, 10.73it/s]

[0.00120007 0.00079026 0.00072319 ... 0.00018779 0.00048293 0.00041876]
[0.00167255 0.00059312 0.00040173 ... 0.00020716 0.00044994 0.0003682 ]
[2.33961538e-03 1.00688912e-03 1.61786510e-04 ... 2.57020755e-04
 3.47961217e-04 5.50444913e-05]


Processing Quantum Reservoir States:  71%|██▊ | 268/375 [00:26<00:09, 10.72it/s]

[0.00192828 0.00062401 0.0004969  ... 0.00030276 0.0005765  0.00011802]
[0.00137122 0.00098336 0.00048734 ... 0.00022505 0.00038263 0.00029521]
[0.00169651 0.00073621 0.00048666 ... 0.00017732 0.00041262 0.00028241]


Processing Quantum Reservoir States:  73%|██▉ | 272/375 [00:26<00:09, 10.68it/s]

[1.94962578e-03 8.07163592e-04 2.85258078e-04 ... 2.39872784e-04
 4.11859456e-04 5.73252472e-05]
[2.86558356e-03 1.07994275e-03 4.38698499e-04 ... 1.55426361e-04
 3.40567558e-04 5.90419412e-05]
[0.00196045 0.00093448 0.00065511 ... 0.00016167 0.00038423 0.00021087]


Processing Quantum Reservoir States:  73%|██▉ | 274/375 [00:26<00:09, 10.71it/s]

[0.00152436 0.0010121  0.00054067 ... 0.00013376 0.00030697 0.00036271]
[2.71016359e-03 7.67364080e-04 3.71572340e-04 ... 1.79559230e-04
 4.29357064e-04 1.32062144e-05]
[0.00217563 0.0012927  0.00043911 ... 0.00015779 0.00043391 0.00017429]


Processing Quantum Reservoir States:  74%|██▉ | 278/375 [00:27<00:09, 10.76it/s]

[0.00148132 0.00077833 0.0007364  ... 0.00016623 0.00045145 0.00036057]
[0.00205704 0.00088727 0.00046246 ... 0.00016217 0.00033803 0.00023188]
[0.00220911 0.00117083 0.0002043  ... 0.00021481 0.00026958 0.0001301 ]


Processing Quantum Reservoir States:  75%|██▉ | 280/375 [00:27<00:08, 10.68it/s]

[2.02901609e-03 6.30098136e-04 6.00142193e-04 ... 2.28770889e-04
 5.62523863e-04 3.29567802e-05]
[0.00150022 0.00133918 0.00034568 ... 0.00015899 0.0002428  0.00038768]
[0.00147647 0.00061738 0.0005466  ... 0.00015841 0.00033593 0.00021547]


Processing Quantum Reservoir States:  75%|███ | 282/375 [00:27<00:08, 10.61it/s]

[2.18642213e-03 6.16604723e-04 3.24335795e-04 ... 2.29971256e-04
 5.82983982e-04 9.84838449e-06]
[0.00242543 0.00140371 0.00039745 ... 0.0001976  0.00036912 0.00024191]


Processing Quantum Reservoir States:  76%|███ | 286/375 [00:28<00:10,  8.84it/s]

[0.00144709 0.00063689 0.0008281  ... 0.00018832 0.00039174 0.00054056]
[0.0017304  0.00082974 0.00028871 ... 0.00016532 0.00031566 0.00018501]
[2.70267737e-03 8.50494949e-04 3.33158800e-04 ... 1.74937974e-04
 4.44959818e-04 3.01338441e-05]


Processing Quantum Reservoir States:  77%|███ | 288/375 [00:28<00:09,  9.29it/s]

[0.00172215 0.00078227 0.00047263 ... 0.00023476 0.00058437 0.00031043]
[0.00135052 0.00073777 0.00056256 ... 0.0002     0.00043362 0.00069982]
[0.00140762 0.00064568 0.00036844 ... 0.00024391 0.00045463 0.0002868 ]


Processing Quantum Reservoir States:  78%|███ | 292/375 [00:28<00:08,  9.98it/s]

[2.16268725e-03 7.78861458e-04 2.62798110e-04 ... 2.66919795e-04
 4.38827694e-04 3.54239670e-05]
[0.00205629 0.00087386 0.00053289 ... 0.00028619 0.00041118 0.00018124]
[0.00110906 0.00080741 0.00063877 ... 0.00017484 0.00046358 0.00031999]


Processing Quantum Reservoir States:  78%|███▏| 294/375 [00:28<00:07, 10.16it/s]

[0.00184686 0.00075397 0.00028592 ... 0.00021087 0.00041056 0.00013396]
[2.21648716e-03 1.16379249e-03 1.86175921e-04 ... 1.82828602e-04
 2.66244052e-04 2.86814954e-05]
[2.00127151e-03 8.42083361e-04 5.49059373e-04 ... 1.21203250e-04
 3.77721172e-04 3.12971091e-05]


Processing Quantum Reservoir States:  79%|███▏| 298/375 [00:29<00:07, 10.36it/s]

[2.06981886e-03 1.00371934e-03 6.13014218e-04 ... 7.97466360e-05
 3.03216894e-04 1.39330167e-04]
[0.00262303 0.00102401 0.00051146 ... 0.00011545 0.00041456 0.0001376 ]
[0.00241451 0.0010369  0.00043844 ... 0.00014465 0.00035974 0.00029636]


Processing Quantum Reservoir States:  80%|███▏| 300/375 [00:29<00:07, 10.49it/s]

[0.00252626 0.00088385 0.00071639 ... 0.00017238 0.00051138 0.00010179]
[0.00213929 0.00120377 0.00055022 ... 0.00017514 0.00043509 0.00036487]
[0.00131076 0.00092087 0.0004686  ... 0.00021988 0.00041303 0.00052945]


Processing Quantum Reservoir States:  81%|███▏| 304/375 [00:29<00:06, 10.57it/s]

[0.00190419 0.00063283 0.00039678 ... 0.0002705  0.00043643 0.00030802]
[0.00146855 0.00101199 0.00023549 ... 0.00025691 0.00034433 0.00015564]
[0.001393   0.00057622 0.0003855  ... 0.00025541 0.00054838 0.00014486]


Processing Quantum Reservoir States:  82%|███▎| 306/375 [00:29<00:06, 10.61it/s]

[0.00138519 0.00086927 0.00019714 ... 0.00021599 0.00029449 0.00017595]
[1.63948686e-03 6.25418108e-04 3.03747649e-04 ... 1.53272590e-04
 4.46762571e-04 1.50229278e-05]
[1.97943274e-03 7.31654696e-04 3.43790507e-04 ... 1.89034079e-04
 4.69065549e-04 3.35104252e-05]


Processing Quantum Reservoir States:  83%|███▎| 310/375 [00:30<00:06, 10.72it/s]

[0.00239424 0.00109156 0.0004823  ... 0.00011304 0.00033257 0.00018483]
[0.00256058 0.00059849 0.00079535 ... 0.00017795 0.00057052 0.00020829]
[0.00220642 0.00123175 0.00046742 ... 0.00018607 0.00046556 0.00026924]


Processing Quantum Reservoir States:  83%|███▎| 312/375 [00:30<00:05, 10.67it/s]

[0.00222323 0.00109512 0.00048364 ... 0.0002431  0.00030271 0.00048214]
[0.00159437 0.00079119 0.00040789 ... 0.00017406 0.00033367 0.00029834]
[0.00161855 0.00075854 0.00026505 ... 0.00015556 0.00045519 0.0001477 ]


Processing Quantum Reservoir States:  84%|███▎| 316/375 [00:31<00:06,  9.02it/s]

[1.90616635e-03 6.05012245e-04 3.00540966e-04 ... 2.38467737e-04
 6.14186865e-04 5.72652446e-05]
[0.00140408 0.00094147 0.00021701 ... 0.00024438 0.00035637 0.00071977]
[1.22518450e-03 3.84191034e-04 4.66980057e-04 ... 2.68182158e-04
 5.41644728e-04 9.12590157e-05]


Processing Quantum Reservoir States:  85%|███▍| 318/375 [00:31<00:06,  9.44it/s]

[2.02245325e-03 8.61846206e-04 2.43113446e-04 ... 1.64607877e-04
 4.63486527e-04 2.45440215e-05]
[0.00270873 0.00075284 0.00049436 ... 0.00022158 0.00045248 0.00011775]
[0.00162881 0.0008835  0.00067057 ... 0.00015798 0.00041936 0.00051157]


Processing Quantum Reservoir States:  86%|███▍| 322/375 [00:31<00:05,  9.99it/s]

[0.00210451 0.00082914 0.00043072 ... 0.00019743 0.00033808 0.00015818]
[2.68182546e-03 1.07231515e-03 2.85522396e-04 ... 1.58087656e-04
 4.05296000e-04 6.62381696e-05]
[0.00148358 0.00101461 0.00035082 ... 0.00017959 0.0003244  0.0001705 ]


Processing Quantum Reservoir States:  86%|███▍| 324/375 [00:31<00:05, 10.17it/s]

[0.00187194 0.00064845 0.00063479 ... 0.00010902 0.00043789 0.00022151]
[0.00185946 0.00098994 0.00027135 ... 0.00016121 0.00037372 0.00020891]
[0.00237698 0.00067541 0.00034791 ... 0.00015502 0.00051101 0.00012846]


Processing Quantum Reservoir States:  87%|███▍| 328/375 [00:32<00:04, 10.42it/s]

[0.00262279 0.00087695 0.00047397 ... 0.00023462 0.00042328 0.00020843]
[0.00171127 0.00104614 0.00068744 ... 0.00014325 0.00043967 0.00033996]
[0.00186248 0.00060783 0.00040345 ... 0.00021837 0.0005101  0.00033654]


Processing Quantum Reservoir States:  88%|███▌| 330/375 [00:32<00:04, 10.53it/s]

[0.00245356 0.00089081 0.00030346 ... 0.00019744 0.00049061 0.00016607]
[0.00181177 0.00075852 0.0004901  ... 0.0003004  0.00055986 0.00039924]
[0.00113571 0.00077774 0.00040888 ... 0.00024101 0.00043249 0.00042238]


Processing Quantum Reservoir States:  89%|███▌| 334/375 [00:32<00:03, 10.57it/s]

[0.0020863  0.00070045 0.00025174 ... 0.0002648  0.00035532 0.00019079]
[1.47067247e-03 8.69603372e-04 2.43679889e-04 ... 2.21152911e-04
 4.09329479e-04 4.63309120e-05]
[1.88132804e-03 5.29084915e-04 4.42360057e-04 ... 2.15276290e-04
 6.49157827e-04 2.41193694e-05]


Processing Quantum Reservoir States:  90%|███▌| 336/375 [00:32<00:03, 10.57it/s]

[0.00186119 0.0011004  0.00032234 ... 0.00019111 0.00033504 0.00032086]
[0.00152128 0.000736   0.0004512  ... 0.00014898 0.00033122 0.00027807]
[2.76494097e-03 7.39381103e-04 4.02162254e-04 ... 1.57841559e-04
 4.01554990e-04 1.27303654e-06]


Processing Quantum Reservoir States:  90%|███▌| 338/375 [00:33<00:03, 10.63it/s]

[2.64294153e-03 1.88276968e-03 3.24161515e-04 ... 9.74773716e-05
 2.38351532e-04 1.66543585e-04]


Processing Quantum Reservoir States:  91%|███▋| 340/375 [00:33<00:04,  8.44it/s]

[1.80105000e-03 5.64449492e-04 8.53477355e-04 ... 9.81272233e-05
 4.35646065e-04 2.97010887e-04]
[0.00224554 0.00099804 0.00038354 ... 0.00013671 0.00041654 0.00018144]
[0.00269237 0.00107862 0.0003441  ... 0.00019525 0.00040501 0.00017977]


Processing Quantum Reservoir States:  91%|███▋| 343/375 [00:33<00:03,  8.27it/s]

[0.00183537 0.00060275 0.00062066 ... 0.0002436  0.00062619 0.00032165]
[0.00142397 0.00113859 0.00040619 ... 0.00020809 0.00029049 0.00057853]


Processing Quantum Reservoir States:  92%|███▋| 345/375 [00:34<00:03,  7.95it/s]

[0.0017234  0.00054286 0.00046704 ... 0.00023223 0.00051301 0.0001906 ]
[0.00183929 0.00087764 0.00015914 ... 0.00028194 0.00034349 0.0001942 ]


Processing Quantum Reservoir States:  93%|███▋| 347/375 [00:34<00:03,  8.21it/s]

[0.00181111 0.00073378 0.00042305 ... 0.00025351 0.00035749 0.00011549]
[0.001426   0.00065263 0.00040396 ... 0.0001973  0.00050211 0.00016375]


Processing Quantum Reservoir States:  93%|███▋| 349/375 [00:34<00:03,  8.05it/s]

[1.76740817e-03 8.15710929e-04 2.25381785e-04 ... 1.98534798e-04
 4.19208655e-04 7.28733350e-05]
[2.35740791e-03 6.01749023e-04 4.54940800e-04 ... 2.20336201e-04
 5.61352617e-04 7.09934111e-05]


Processing Quantum Reservoir States:  94%|███▋| 351/375 [00:34<00:02,  9.14it/s]

[0.00207379 0.00094642 0.00055333 ... 0.00021212 0.00053101 0.00035218]
[0.00187203 0.0009599  0.00061623 ... 0.00018319 0.00035888 0.00045581]
[0.00217035 0.00084506 0.00040068 ... 0.00022341 0.00035433 0.00013785]


Processing Quantum Reservoir States:  94%|███▊| 354/375 [00:35<00:02,  9.41it/s]

[2.45625688e-03 1.09191567e-03 2.56292097e-04 ... 1.77059040e-04
 3.48685870e-04 9.93831529e-05]
[0.00161749 0.00077315 0.00049372 ... 0.00020395 0.0004444  0.00014511]


Processing Quantum Reservoir States:  95%|███▊| 356/375 [00:35<00:01,  9.91it/s]

[0.00158925 0.0008688  0.00035157 ... 0.00015747 0.00043825 0.00034036]
[0.00169113 0.00079823 0.00024523 ... 0.00020071 0.00033466 0.00019359]
[2.13629455e-03 6.57545631e-04 3.88600289e-04 ... 1.72669989e-04
 5.33673007e-04 1.31358015e-05]


Processing Quantum Reservoir States:  96%|███▊| 360/375 [00:35<00:01, 10.35it/s]

[0.00256974 0.00111982 0.00038903 ... 0.00015782 0.00036683 0.00018588]
[0.0019114  0.00081252 0.00074118 ... 0.00012771 0.00038644 0.00033716]
[0.00227548 0.0007766  0.00037964 ... 0.00020011 0.00045067 0.00021856]


Processing Quantum Reservoir States:  97%|███▊| 362/375 [00:35<00:01, 10.47it/s]

[2.78968374e-03 1.07540967e-03 3.36247674e-04 ... 1.99706098e-04
 4.20672119e-04 9.27553372e-05]
[0.00189313 0.00075374 0.00059832 ... 0.00023736 0.00058555 0.00032297]
[0.0013748  0.00087984 0.00046491 ... 0.00022411 0.00047762 0.00052054]


Processing Quantum Reservoir States:  98%|███▉| 366/375 [00:36<00:00, 10.60it/s]

[0.00182946 0.00071202 0.00037766 ... 0.00028932 0.00050602 0.00028477]
[0.00157744 0.00089368 0.00023425 ... 0.00030514 0.00037304 0.00017757]
[1.94084926e-03 6.75566811e-04 4.47338305e-04 ... 2.36157908e-04
 4.37408557e-04 6.70882555e-05]


Processing Quantum Reservoir States:  98%|███▉| 368/375 [00:36<00:00,  8.36it/s]

[0.00160565 0.00087366 0.00036751 ... 0.00021951 0.00047364 0.00012019]
[0.00160246 0.00077811 0.00036664 ... 0.00022014 0.00049994 0.00013977]
[0.00209433 0.00084146 0.00040454 ... 0.00021908 0.00041181 0.00010088]


Processing Quantum Reservoir States:  99%|███▉| 372/375 [00:36<00:00,  9.40it/s]

[2.10016443e-03 1.11713096e-03 5.06656246e-04 ... 1.55579799e-04
 3.62585935e-04 9.77861445e-05]
[2.19411631e-03 9.15282259e-04 6.88079747e-04 ... 1.54998759e-04
 4.47918787e-04 8.96096022e-05]
[0.00222668 0.00138313 0.00045672 ... 0.00015761 0.00029731 0.0001757 ]


Processing Quantum Reservoir States: 100%|████| 375/375 [00:37<00:00, 10.09it/s]

[0.00217553 0.00108615 0.00044773 ... 0.00015334 0.000275   0.00016862]
[0.00168024 0.00105374 0.00043661 ... 0.00013044 0.00025112 0.00011448]
[1.91475305e-03 1.11938036e-03 3.85623862e-04 ... 7.19970242e-05
 2.28424114e-04 1.25902050e-04]
Quantum Reservoir States Shape: (375, 4096)


In [11]:
print("ESP Satisfied:", verify_ESP(cprc_states))

TypeError: verify_ESP() missing 1 required positional argument: 'reservoir_states_2'

In [38]:
mc = memory_capacity(cprc_states, X_train[:, 0], max_delay=50)
print(f"Memory Capacity: {mc}")

Memory Capacity: 0.00042546882875182934


In [34]:
rmse = res_task(cprc_states, y_train)
print(f"NARMA-10 RMSE: {rmse}")

NARMA-10 RMSE: 0.09964828416938289


In [13]:
gbs_states = []
for sample in tqdm(X_train, desc="Processing Quantum Reservoir States"):
    state = gbs.Probs(sample)
    gbs_states.append(state)

gbs_states = np.array(gbs_states)
print("Quantum Reservoir States Shape:", gbs_states.shape)

Processing Quantum Reservoir States: 100%|████| 375/375 [13:24<00:00,  2.14s/it]

Quantum Reservoir States Shape: (375, 4)


In [14]:
print("ESP Satisfied:", verify_ESP(gbs_states))

ESP Satisfied: False


In [15]:
mc = memory_capacity(gbs_states, X_train[:, 0])
print(f"Memory Capacity: {mc}")

Memory Capacity: 0.024299781896090944


In [16]:
rmse = res_task(gbs_states, y_train)
print(f"NARMA-10 RMSE: {rmse}")

NARMA-10 RMSE: 0.10991667636385466


In [72]:
import numpy as np

def extract_expectation_values(prob_list):
    n_qubits = int(np.log2(len(prob_list)))
    z_expectations = np.zeros(n_qubits)
    num_states = 2 ** n_qubits 
    for state_index in range(num_states):
        bitstring = format(state_index, f"0{n_qubits}b")  # Convert index to binary bitstring
        bit_values = np.array([1 if bit == '0' else -1 for bit in bitstring])  # Convert to ±1
        z_expectations += prob_list[state_index] * bit_values  # Weighted sum
    return z_expectations

prob_list = np.random.dirichlet(np.ones(2**n_qubits), size=1)[0]  # Random probability distribution

expectation_values = extract_expectation_values(prob_list)
expectation_values


array([-0.04968907,  0.04859069,  0.01703941])

In [70]:
int(np.log2(len(prob_list)))

3